### ISSUE TITLE
Can Approvers edit and delete comments?  If so, their own comments only?

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#1]

**Comment by ryant26** [comment]
I think delete should be the only option, edit can be an enhancement.

**Comment by kuzi117** [comment]
I think this is looking a bit far forward for now, since adding comments isn't even there yet. I think if this gets added as an enhancement it should be low priority.

As for the actual questions, I agree with Ryan. Make comment > delete > edit; only modify your own comments.

**Comment by kdbanman** [comment]
I feel this is sufficiently answered to close.  FWIW, only adding comments is mentioned in the user stories.  If we get around to making a Use Case, it can be a low priority one.
