### ISSUE TITLE
Add distance-based color-coding to expense claims list

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#107]
Refer to US02.03.01

**Comment by therabidsquirel** [comment]
I know we talked about this two labs ago, but I'm having trouble remembering. How many levels of distance do we want to have, and what would be the approximate kilometer thresholds? I'm thinking text labels for various levels are a good idea, as it provides another means of gauging distance. I'm thinking of using a TextView I can switch out the label for and change the color of the text/background. I'm kind of terrible with distances, but how do these sound?

- Very Nearby, < 100 km
- Nearby, < 500 km
- (I can't think of a good label), < 3 000 km
- Distant, < 10 000 km
- Very Distant, no max

@kdbanman's very helpful [eClass post](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=486352) about color.

Color doesn't have to be confined to a label, as it can be interpolated based on distance. For example (I'm not familiar with HSV), using an HSV of (0,0,100) for no distance and (0,100,100) for max distance (>= 20 000 km). I do like interpolating the color, as it provides a very smooth spectrum then.

I've about got the implementation in, I'm just concerned about valid thresholds/labels/colors, all from a usability standpoint. I'm open to anything.

**Comment by TheLastBanana** [comment]
I think we discussed having a spectrum based on the furthest destination.
So if the colors range from green to red, green would be your closest claim
and red would be your furthest claim, regardless of the actual distance.

**Comment by therabidsquirel** [comment]
I'm not sure I like that actually, having a relative spectrum instead of an absolute one. If that were the case, a claim could be a certain color indicating its distance. A bunch of claims could be added or modified so that claim's color has now drastically changed, despite the claim not having changed and the user's home location not having changed.

While relative does have it's advantages, I feel absolute is our best bet.

**Comment by TheLastBanana** [comment]
In that case, you may want to opt for an exponential scale. Otherwise, the difference in color between 100 km and 500 km will be nearly indistinguishable.

**Comment by therabidsquirel** [comment]
Ah, very good point on the exponential scale, thank you. I did not think about that.
