### ISSUE TITLE
Add user stories to use cases for geolocation

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#108]

**Comment by kdbanman** [comment]
I don't think I'll be able to pull this off before the deadline guys.  I've been going nonstop on the cache for days and there are still same hurdles there.  Sorry.

**Comment by therabidsquirel** [comment]
I won't be able to do it either. I've been working almost nonstop the whole weekend, and once I finish up my next push I've two other assignments due Wednesday I haven't started yet.

**Comment by ryant26** [comment]
New use cases start [here](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#ucselectgeolocation)
