### ISSUE TITLE
Implement UC.ListExpenseClaimsClaimant

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#11]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#uclistexpenseclaimsclaimant)

**Comment by ryant26** [comment]
Needs tests. Otherwise done.

**Comment by ryant26** [comment]
a2b32e64df13ff97f1b68a3b0827a324ece5d98b
