### ISSUE TITLE
DataSource should update listeners on UI thread

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#115]
This is mainly for testing but really it should be the case. I'm assuming the cache data source will be using AsyncTasks to come back to running on the UI thread and the other derivations should probably hold to this.
Beyond this it's needed in testing. This line [here](https://github.com/CMPUT301W15T07/TravelTracker/blob/0567bc61c59628f8a7bb4433061352af203959a2/tests/src/cmput301w15t07/TravelTracker/test/activity/ExpenseItemsListActivityTest.java#L112) adds an item to the datasource, which in turn updates all listeners (the activity being tested) which then causes the list to be rebuilt and rerendered. Rerendering is only allowed on the UI thread and so the test errors out.
Ryan's ClaimList tests are also affected by this (plenty of run on UI thread calls).

**Comment by kdbanman** [comment]
Thanks for the tip.

**Comment by kuzi117** [comment]
This is closed from the InMemoryDataSource point of view. If @kdbanman is ok with it it can be closed.

**Comment by kdbanman** [comment]
The cache datasource is designed with this in mind.
