### ISSUE TITLE
ExpenseItem Currency being set to CAD on item open for generated data

### ISSUE THREAD

**Issue by skwidz** [CMPUT301W15T07/TravelTracker#116]
When an expense item is opened the currency is being set to CAD before the item is opened.
This only seems to happen for the data that is generated, not for any data that is created by the user. If a user modifys a generated claim, the changes will be persistant and will not be changed when entering expense item info. This seems to be happening before the ExpenseItemInfo activity is loaded.  

REPRO: 
1. open expense item list for in progress claim
2. click on expense item
3. item currency is changed to CAD  
4. expense item is opened

REPRO
1. open expense item list for in progress claim
2. click on expense item
3. item currency is changed to CAD  
4. expense item is opened
5. change currency to USD 
6. Return to expense item list. 
7. see that currency remains USD 
8. click on expense item again
9. expense item is opened
10. currency remains USD.

**Comment by therabidsquirel** [comment]
I remember mentioning this at least once, and I can see it hasn't been acted on yet, bet our currency in item is of type Currency, not our own ItemCurrency. I will go ahead and change this.
