### ISSUE TITLE
Add geolocation to expense item views.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#118]
- Expense items have an optional geolocation.
- In viewing the list of expense items, you only need to see whether the expense item has a geolocation or not.

**Comment by therabidsquirel** [comment]
I can take this on, shouldn't take that long.

**Comment by kuzi117** [comment]
Famous last programming words. See you 5 minutes before deadline with a 300 line, ducktaped-together work around! :P

**Comment by therabidsquirel** [comment]
Take that. :P Finished in cd3b30c.
