### ISSUE TITLE
Implement UC.ListExpenseClaimsApprover

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#12]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#uclistexpenseclaimsapprover)

**Comment by ryant26** [comment]
needs to show approver,  waiting on (Issue81)[https://github.com/CMPUT301W15T07/TravelTracker/issues/81]. Also needs tests, then done.

**Comment by therabidsquirel** [comment]
For viewing a list of claims as either approver or claimant, the length of the view for a claim in the list seems to be determined by the currency totals on the right hand side. As a result, if there aren't many expense items and therefore few totals while there are also lots of destinations, then the destinations get cut off and are not all displayed.

**Comment by ryant26** [comment]
Really, that's interesting. I will look into that, thanks

**Comment by ryant26** [comment]
a2b32e64df13ff97f1b68a3b0827a324ece5d98b
