### ISSUE TITLE
Submitting a claim with incomplete information.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#120]
From [here](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=480212):
> A claim without destinations or descriptions is incomplete.

Currently when submitting a claim, only the incompleteness indicators on the claim's items are checked. From the eClass post we also want to check if:

- The claim has a non-empty description.
- The claim has at least one destination.

This covers everything at the claim level, as dates are automatically set.

We also might want to check a selection of things from items as well (which is trivial given the items are already being iterated through):

- If the item's description is non-empty.
- If the item's category isn't set to No Category. Maybe not, what if there's a category we don't cover?
- If the item's amount is non-zero. Probably not actually, in case you're entering something that was free? But then a currency doesn't make sense in that case, as there's no difference between 0 CAD and 0 EUR.

**Comment by kdbanman** [comment]
You're right, the two claim warnings should be in there.  Each should have a specific warning message for the dialog.

For the item ones:

> - If the item's description is non-empty.
> - If the item's category isn't set to No Category. Maybe not, what if there's a category we don't cover?
> - If the item's amount is non-zero. Probably not actually, in case you're entering something that was free? But then a currency doesn't make sense in that case, as there's no difference between 0 CAD and 0 EUR.

Since the user is prompted with a dialogue no matter what, it is only a bonus to usability if the user is informed about these item-related things.  Again, they need good, specific messages.

**Comment by therabidsquirel** [comment]
I can take this on, I just want to be sure people don't disagree with me before I start adding a bunch of stuff.

Specific warning messages is a good idea, but how would that work if you had lots of different messages? With destination editing for example, since neither location nor geolocation can be blank, I have three different warning messages that can be displayed (one for each of the two and one for both). That way, the warning message always tell the user exactly why the edit wasn't accepted.

If we're talking about two claim fields and several fields from items, not only would the number of combination messages be tedious to work with and a bad idea to do, but one message couldn't reasonably tell you six things are wrong (empty claim description, no claim destinations, expense items marked as incomplete, empty expense item descriptions, expense items not given categories, expense items with zero amounts).

The alternative is you're just told one thing that's wrong (according to wrongness priority hierarchy), and even if everything else is wrong a better worded "and other stuff" could be appended to the message (worst case 7 unique messages to create in strings.xml). Another alternative is to drop the "and other stuff", and just warn of one thing at a time (worst case 6 unique messages to create in strings.xml).

**Comment by TheLastBanana** [comment]
I think having one warning at a time is reasonable. In a perfect world it would show you everything, but I don't know if it's worth the trouble right now.

**Comment by therabidsquirel** [comment]
Yeah, one at a time works. Why can't I have a perfect world though? :/ I will go ahead and do this. Unless anyone has objects, I will only include at least one claim destination, a non-empty claim description, and non-empty expense items descriptions. I will not consider expense item categories or [amounts](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=454918) when considering claim completeness.

**Comment by kdbanman** [comment]
> The alternative is you're just told one thing that's wrong (according to wrongness priority hierarchy)

That sounds like the best tradeoff to me.
