### ISSUE TITLE
Empty tests in ClaimInfoActivityTest.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#121]
Currently 4 test methods are empty.

**Comment by kdbanman** [comment]
Those are from the use cases I did.  The cache has a higher priority for me for now.

**Comment by therabidsquirel** [comment]
All of the empty test methods I created issues for would be from the use cases. Functionality certainly has higher priority at this point, I simply created these to better keep track of what's left.

**Comment by ryant26** [comment]
1b197c41773d336861db014272c3edf47930c0e4
