### ISSUE TITLE
GSON no-args constructor.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#129]
To replicate:

1. uncomment the `new CacheDataSource()` injection line in DataSourceSingleton.java (line 53).
2. start TravelTracker and log in as a claimant.
3. create at least one Claim (or Item or Tag)
4. delete one or more of the things you created in 3.
5. close the app (completely)
6. restart the app
7. GSON crashes as detailed below

Only when deserializing a list of DeletionFlags for the CacheDataSource (line 106), GSON cannot find the no-args constructor of Document().  It can for other serialization/deserialization tasks.  Perhaps it's because the Document is wrapped by DeletionFlag in this case.

```
04-06 09:19:04.112: E/AndroidRuntime(10083): FATAL EXCEPTION: main
04-06 09:19:04.112: E/AndroidRuntime(10083): java.lang.RuntimeException: Unable to start activity ComponentInfo{cmput301w15t07.TravelTracker/cmput301w15t07.TravelTracker.activity.LoginActivity}: java.lang.RuntimeException: Failed to invoke private cmput301w15t07.TravelTracker.model.Document() with no args
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.os.Looper.loop(Looper.java:137)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at java.lang.reflect.Method.invoke(Method.java:511)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at dalvik.system.NativeStart.main(Native Method)
04-06 09:19:04.112: E/AndroidRuntime(10083): Caused by: java.lang.RuntimeException: Failed to invoke private cmput301w15t07.TravelTracker.model.Document() with no args
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:107)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:186)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.Gson.fromJson(Gson.java:810)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at com.google.gson.Gson.fromJson(Gson.java:775)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at cmput301w15t07.TravelTracker.util.GsonIOManager.load(GsonIOManager.java:68)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at cmput301w15t07.TravelTracker.util.PersistentList.loadList(PersistentList.java:203)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at cmput301w15t07.TravelTracker.util.PersistentList.<init>(PersistentList.java:63)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at cmput301w15t07.TravelTracker.model.CacheDataSource.<init>(CacheDataSource.java:106)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at cmput301w15t07.TravelTracker.model.CacheDataSource.<init>(CacheDataSource.java:91)
04-06 09:19:04.112: E/AndroidRuntime(10083): 	at cmput301w15t07.TravelTracker.DataSourceSingleton.getDataSource(DataSourceSingleton.java:55)
```

**Comment by kdbanman** [comment]
I suspect this is because of the stackoverflow solution to GSONing lists of complex types.  From PersistentList line 220:

```
public class ArrayListType implements ParameterizedType {
		
		@Override
		public Type[] getActualTypeArguments() {
			return new Type[] {wrappedClass};
		}
	
		@Override
		public Type getOwnerType() {
			return null;
		}
	
		@Override
		public Type getRawType() {
			return ArrayList.class;
		}
	}
```

The `getRawType()` is fine, but hard coding the `getActualTypeArguments()` array may be obscuring something important.

**Comment by kdbanman** [comment]
If you want to try and debug this, uncomment the `new CacheDataSource()` injection line in DataSourceSingleton (line 53).

Set a breakpoint at line 106 of CacheDataSource and start stepping in.  The error occurs when GsonIOManager (line 68) tries to load the PersistentList<DeletionFlag>.

Context:  GsonIOManager handles serializing and deserializing PersistentList<UUID> just fine, same with all of our Document subclasses.  But a PersistentList<DeletionFlag> chokes it with the stacktrace above.

**Comment by kdbanman** [comment]
I think I figured this out.  The DeletionFlag has a Document as an attribute, not a subclass of Document.  When GSON tries to deserialize, it takes that literally and tries to construct a Document, which is abstract.  That can't be instantiated.

I either need to make PersistentList take a deserialization Type for each element, or I need to maintain a deletion list for each subclass of Document so that PersistentList stays consistent.

**Comment by kuzi117** [comment]
> GsonIOManager handles serializing and deserializing PersistentList just fine, same with all of our Document subclasses. But a PersistentList chokes it with the stacktrace above.

You said persistent list twice, once saying it was ok and once bad. Can you clarify?

**Comment by kdbanman** [comment]
Woops, markdown swallowed my generics because it thought they were HTML.  I'll edit, gimme a sec.

**Comment by kdbanman** [comment]
Edited.

**Comment by kdbanman** [comment]
I refactored to have multiple deletion lists in the CacheDataSource - one per type so that I could give GSON proper information about the type within the list for serialization.

A different bug, but similar.  My hunch is growing stronger that the Stackoverflow solution to parametrized types is no good for complex stuff like types parametrized by other types.

**Comment by kdbanman** [comment]
The refactor is on the branch `cache-bug`.  The DataSourceSingleton is already in use.

**EVERY TIME IT CRASHES, EITHER CLEAR THE USER DATA ON THE EMULATOR OR GO INTO THE DDMS AND REMOVE `/data/data/cmputblablabla/files/`FILES BY HAND**

**Comment by kdbanman** [comment]
Post-refactor, replicate by trying to delete a claim or item or tag.

GSON is complaining with better errors now, but I'm still confused because it's refusing to serialize `cmput301w15t07.TravelTracker.model.Claim`, which it's doing just fine in FileSystemHelper.

The new failure stacktrace follows:

```
04-06 11:56:15.190: E/AndroidRuntime(1803): FATAL EXCEPTION: main
04-06 11:56:15.190: E/AndroidRuntime(1803): java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: cmput301w15t07.TravelTracker.model.Claim. Forgot to register a type adapter?
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:67)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:61)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.Gson.toJson(Gson.java:600)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.google.gson.Gson.toJson(Gson.java:579)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at cmput301w15t07.TravelTracker.util.GsonIOManager.save(GsonIOManager.java:97)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at cmput301w15t07.TravelTracker.util.PersistentList.saveList(PersistentList.java:212)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at cmput301w15t07.TravelTracker.util.PersistentList.add(PersistentList.java:69)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at cmput301w15t07.TravelTracker.model.CacheDataSource.deleteClaim(CacheDataSource.java:158)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at cmput301w15t07.TravelTracker.activity.ClaimInfoActivity.deleteClaim(ClaimInfoActivity.java:425)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at cmput301w15t07.TravelTracker.activity.ClaimInfoActivity$8.onClick(ClaimInfoActivity.java:407)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at android.os.Looper.loop(Looper.java:137)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at java.lang.reflect.Method.invoke(Method.java:511)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-06 11:56:15.190: E/AndroidRuntime(1803): 	at dalvik.system.NativeStart.main(Native Method)
```

I need to stop dealing with this and sleep for a while.

**Comment by kdbanman** [comment]
@kuzi117 , ^this^ is the current state of things.

**Comment by kuzi117** [comment]
This might be it... http://stackoverflow.com/a/11459691/2379240

**Comment by kuzi117** [comment]
Adding expose to everything _does_ work. So it would seem that it's being subtly wrapped by some type and we can't see it. I guess it really does need a custom adapter.

**Comment by kuzi117** [comment]
> My hunch is growing stronger that the Stackoverflow solution to parametrized types is no good for complex stuff like types parametrized by other types.

I don't think it is.. I just committed (this)[https://github.com/CMPUT301W15T07/TravelTracker/commit/d1da2c63518a470216e955d96afc907686f44ca6] which is theoretically the same as what you were constructing before. The error didn't change. It also didn't change when I put (this adapter in)[https://github.com/CMPUT301W15T07/TravelTracker/blob/cache-bug/src/cmput301w15t07/TravelTracker/model/TagTypeAdapter.java] and registered it (like this)[https://github.com/CMPUT301W15T07/TravelTracker/commit/0db1530e46060ae0f053c694aadb9a3dafac72c6].

**Comment by kdbanman** [comment]
> Adding expose to everything does work. So it would seem that it's being subtly wrapped by some type and we can't see it. I guess it really does need a custom adapter.

I don't see this in the commit history.  I'd like to see it in another branch if it's recoverable.  It's cool if not.  In an earlier version I was using `@Expose` on all the fields I needed to include in serialization, but I found it was easier to use `transient` on the fields I wanted to exclude.

**Comment by kdbanman** [comment]
> I just committed this which is theoretically the same as what you were constructing before.

`(new TypeToken<ArrayList<T>>() {}.getType()` within a class that's parameterized by `T` does change things, but not for the better.  Java's type erasure will confuse GSON and make it deserialize the parametrized type as a `String`, rather than whatever class it should be.

**Comment by kuzi117** [comment]
I never committed the expose stuff, though it's easy enough to try for yourself. Just add the excludeFieldsWithoutExposeAnnotation() and then expose on stuff you want to bring. Though I didn't see expose actually do anything.

**Comment by kdbanman** [comment]
The failure is isolated and quick to reproduce in PersistentListTest now. (on `cache-bug` branch).  The `PersistentList<ArrayList<Claim>>` serializes just fine, `PersistentList<DeletionFlag<Claim>>` fails with

> java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: cmput301w15t07.TravelTracker.model.Claim. Forgot to register a type adapter?

**Comment by kdbanman** [comment]
FYI: @kuzi117 is writing a TypeAdapterFactory for DeletionFlag on branch `cache-bug2`.

Initial plan and feedback is [here](https://github.com/CMPUT301W15T07/TravelTracker/commit/39403dceb32c0f999a378d8c2e683bf623641625?diff=unified)

**Comment by kuzi117** [comment]
I'm like 95% sure this is closed. I'll let @kdbanman close when he's sure though.
