### ISSUE TITLE
View geolocations when claim isn't editable.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#130]
- Home geolocations are fine.
- Destination geolocations need to be viewable *all the time by both claimants and approvers*. As clicking on destinations is currently disabled for approvers and uneditable claims, one cannot see the button to view the geolocation. Must be sure to disable all editing of the destination's location, geolocation, and reason when appropriate, while always being able to see the geolocation.
- Expense item geolocations need to be viewable *all the time by only claimants*. No user stories specifiy approvers needing to see expense item geolocations. The problem otherwise is similar to destination geolocations.

**Comment by TheLastBanana** [comment]
Closed by 04664f7eff24981353baf003fe84a47bda8857c9

**Comment by therabidsquirel** [comment]
Most short-lived issue ever.

**Comment by TheLastBanana** [comment]
#rekt
