### ISSUE TITLE
Adding a new destination in ClaimInfo won't show the new destination until the LinearLayout refreshes.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#133]
This (4cd751a) still doesn't fix it. Upon adding a new destination, the LinearLayout doesn't refresh with the new view until its updateActivity is called, such as from onResume. I've tried many different ways to update the LinearLayout, but I can't get it to work. I tried refactoring the whole thing again, this time having DestinationAdapter extened ArrayAdapter<Destination>. I spent probably an hour on that, and couldn't get views to show at all, so I just reverted all of it. I've tried running postInvalidate, or running the addView as well as invalidate on the LinearLayout.post(Runnable()). I tried rebuilding the whole LinearLayout every time a new destination is added, still nothing. I do not understand at all.

Furthermore, deleting always refreshes the LinearLayout, but it's not doing anything different. It's calling LinearLayout.removeView, while adding is calling LinearLayout.addView. I don't know why one would seemingly cause an update and the other wouldn't. If someone else knows an answer, please help.

**Comment by TheLastBanana** [comment]
To reproduce, the destination has to be set from the "set location on map" button rather than "set to current location."
