### ISSUE TITLE
Implement UC.EditExpenseItem

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#16]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#uceditexpenseitem)

**Comment by therabidsquirel** [comment]
This doesn't seem to be fully working. The currency type doesn't appear to successfully read from the spinner. It's hard to tell what the currency is, as the spinner always shows CAD upon starting the activity, but from giving an expense item a very high amount and viewing the totals in ClaimInfo you can see what the currency type of that item is, and trying to change it has no effect.

I assume something similar would happen with the category spinner, as it always displays ACCOMMODATION, but there's no way to check as the category isn't listed anywhere else.

Also, this has more to do with viewing, though it affects editing. The completeness check box is always checked when starting ExpenseItemInfo, so if an item is currently set to incomplete, you have to uncheck then recheck the box to set it to complete.

**Comment by skwidz** [comment]
The loading error is errors in the generated data, not in the activity. The currency isn't in the right format and the category just isn't set.

**Comment by therabidsquirel** [comment]
Ah, nevermind then. If it's just the generated data you can close this again.

**Comment by skwidz** [comment]
I'll recheck the checkbook thing, if you edit an item then back out and reopen the item it loads properly

**Comment by therabidsquirel** [comment]
No matter how many times I back out to any of the parent levels, whether it says the item is complete or not, I'm always seeing the check box checked upon clicking on any expense item.

**Comment by ryant26** [comment]
Setting a date for a new expense on a new claim is crashing the app. Is this a known bug?

**Comment by skwidz** [comment]
@ryant26 it wasn't know to me although it's crashes when exiting the app as well. I can look into both of those. 

@the_rabidsquirel I'll look at that when I get back to school. That would have been in the last change I made last night so it entirely possible I just broke it trying to fix it

**Comment by ryant26** [comment]
@skwidz I fixed the date crash

**Comment by kdbanman** [comment]
@skwidz, @therabidsquirel, the checkbox always true bug is fixed in b7038f21fb04e0e2aabf5758c1c11bc35806d09f

**Comment by kdbanman** [comment]
I reopened the issue.  this activity crashes a lot and we need to fix that before submission time.

**Comment by therabidsquirel** [comment]
This is actually done now. Tests are covered in #123.
