### ISSUE TITLE
Implement UC.CreateExpenseItem

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#19]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#uccreateexpenseitem)

**Comment by kuzi117** [comment]
Also closed in 6a73411.

**Comment by therabidsquirel** [comment]
Creating a new expense item, then backing out, always seems to crash the app.

Also, expense items can be added from ClaimInfo as well, though currently the function for that menu item is empty. That could probably be a copy/paste of code from ExpenseItemsList's menu item though.

**Comment by therabidsquirel** [comment]
After I reorganized the structure of ExpenseItemInfoActivity to match that of ClaimInfoActivity, I find it no longer crashes at all upon making a new expense item from either ClaimInfoActivity or ExpenseItemsListActivity. Maybe I fixed it through the reorganization, or maybe someone else fixed it? If other people can verif this doesn't crash we can close this.

**Comment by kuzi117** [comment]
I think this can be closed again.
