### ISSUE TITLE
Can users edit their own names?

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#2]

**Comment by ryant26** [comment]
I think we should mark this as enhancement. Would require an account settings area.

**Comment by kdbanman** [comment]
Just to clarify, the things I've marked as "questions" are things that aren't specified in the user stories and need clarification from a TA or Abram.  This is just a way to get some team input before asking officially.

Things currently marked as "enhancements" are known requirements/use cases.  It's probably a bad tag name, so I want the planning team to weigh in on how issues, issue tags, and milestones are used. @kuzi117 , @TheLastBanana , can you let us know when you get a chance?

**Comment by TheLastBanana** [comment]
I think it's reasonable to keep known requirements and potential requirements separate. Once we know for sure that it's needed, we can mark it as an enhancement.

**Comment by kuzi117** [comment]
Agree with Ryan in that this is another enhancement, but in regards to how to answer this question, I feel like we've already answered this question in Slack chat.

If (for now, until *possible* spec changes) we're modeling a user as a just a wrapper for a string, no UUID or special auth, then changing your name is just a simple as backing up to the root of the activity stack and logging in with a different name.

Now if we're talking about changing current items in the database whose names are the same as the current logged in user to be attached to a different user name then it's another issue entirely and I don't think it should be allowed. (E.G. a user Bill has some number of database items (tags/claims/etc.) attached to his name, Fred similarly has some number of items. Fred changes his name to Bill and then back to Fred. Does that change his items to be named Fred, and then include Fred's items to be switched back to Bill?)

**Comment by kdbanman** [comment]
I feel like this question has been resolved:

- Users log in with whatever name
- We treat that as their unique user ID
- We hide that beneath a User model object, which we *can* extend with a password hash, non-unique first and last names, etc

So for current requirements, if we already have a "Bob" and another Bob wants to play the claim game, then he logs in as "Bob2" or something.  If requirements change later, we can allow them to both change their name to bob, but leave their IDs as Bob and Bob2.

If there are no complaints, this issue can probably be closed.

**Comment by TheLastBanana** [comment]
Yeah, that sounds good to me.
