### ISSUE TITLE
Implement UC.ListExpenseItems

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#22]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#uclistexpenseitems)

**Comment by therabidsquirel** [comment]
Currently only completeness, date, description, and receipt image are shown in listing. According to US05.01.01 we also need to show category, amount, and currency.

**Comment by therabidsquirel** [comment]
I also just realized per US08.04.01 that approvers see all of the same information as claimants when viewing the list of expense items **except** for the completeness indicator, as much like claim tags those are solely a means of organization for the claimant.

**Comment by ryant26** [comment]
I'm noticing on the long press that only about half of the row item is "long click-able" or darkening as the press is being held. Is this just a local bug for me or are you experiencing it too?

**Comment by therabidsquirel** [comment]
I'm experiencing this as well. It has something to do with the picture, as the non-clickable space is taken up entirely by itemsListItemViewReceiptImageView.

**Comment by kuzi117** [comment]
Yeah the image part doesn't highlight. Also I'll do this tonight then after I figure out what it should look like and it to the UI UML.

**Comment by kuzi117** [comment]
Actually, WTF. Apparently I'm just blind and the UML already has that stuff and I didn't put it in. My bad.

**Comment by kuzi117** [comment]
This is done, since before we submitted for the milestone.
