### ISSUE TITLE
Create UML diagram(s)

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#24]
We currently have an early UML diagram of the our data model. We should make sure it's finished. We probably also want UML diagrams for each of the activities.

**Comment by kuzi117** [comment]
Need to design the `DataSource` interface and add that.

These seem obvious:
`ds.getClaim(int id)` (Returns a claim by ID)
`ds.getItem(int id)` (Returns an item by ID)

If data source is also our main controller then we'll also need listeners. It's arguable that we put these into a second interface but I'll still suggest them:
`ds.addListener(Listener l)` (Adds a listener, implies that we also need a `Listener` interface)
`ds.update()` (Calls `update()` on all registered `Listener`s)

We'll also need to create new instances of everything:
`int id = ds.createClaim(...)` (Returns the created claim's ID, don't know what the arguments if any will be)
`int id = ds.createItem(...)` (Returns the created item's ID, don't know what the arguments if any will be)

In the opposing direction:
`ds.deleteClaim(int id)` (Deletes the claim by id)
`ds.deleteItem(int id)` (Deletes the item by id, implies remove item id from `Claim`s it's in)

I've also considered a model where the `getClaim`/`getItem` don't exist and the DataSource handles all interaction in the model. Though it might seem like more work one change would be that DataSource would be handling all of the updating itself and we wouldn't have a `Claim`/`Item` calling `ds.update()` (decouples `Claim`/`Item` from `DataSource`).
`ds.addItemToClaim(int cID, int iID)` (Adds the item to a claim)
`ds.removeItemFromClaim(int cID, int iID)` (Removes the claim from an item)

How the backend data is maintained is then specific to implementation. I can't think of anything else needed in the interface though I'm pretty sure I've missed something.

**Comment by TheLastBanana** [comment]
We also need to model users and tags!

Just to clarify: is the idea here that a Claim would not actually contain a list of Items, but a list of UUIDs which represent items?

Re: having the DataSource handle all the interaction within the model, I think that's going a little overboard. That's pretty much the definition of a god class.

**Comment by kuzi117** [comment]
You're right about the god class thing, I'm just gonna strike that.
Yes the idea was that there would be a list of UUID's rather than the actual items, but our current UML disagrees.

**Comment by ryant26** [comment]
(Long Read Warning) I'm going to weigh in here and throw a few of my ideas out:

1.) I think we should try to avoid the term "listeners" since it conflicts a bit with android button listeners, etc. Lets use observers (since we are using "Observer MVC").

2.)  The DataSource is still our model, the controllers are the activities, and anything with "view" in the name (listView) or defined in XML is the view. 

I know these terminology points may seem like I'm splitting hairs but I think it's important that we are all on the same page so that we avoid misunderstandings as much as possible.

3.) I have always felt that modeling data client side so that it needs as little processing as necessary to be stored server side is the most effective, I think everyone should read (or skim) [Elastic Search - Handling Relationships](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/relations.html#relations) so you can get an idea of how this data will look server side. Especially since there are some key relationships in our data.

4.) >Yes the idea was that there would be a list of UUIDs rather than the actual items, but our current UML disagrees.

We learned in 291 that a many-to-one relationship puts the extra field on the "many" side. I think expense items should have a parentClaim, or claimID field instead of the claim maintaining a list of expense ID's. (This has a couple of advantages, I'd be happy to elaborate if anyone feels unconvinced)

5.) I think we should apply the trend from the claim-item relationship to tags-users (also many-to-one) relationship. I think we should have a userID associated with every tag.

6.) To address the god class problem I see the following as a first draft:
```
observers : ArrayList<Observer>
items : ArrayList<Items>
claims : ArrayList<Claims>
------------------------------------------------------
+ addClaim(Claim newClaim)
+ addExpense(Expense expense)
+ addObserver(Observer obs)
+ deleteClaim(UUID id)
+ deleteExpense(UUID id)
+ getClaim(UUID id):Claim
+ getAllClaims():Collection<Claim>
+ getExpense(UUID id):Item
+ getAllExpenses():Collection<Item>
+ notifyDataChanged()
- updateObservers()

Convenience Methods:
+ deleteClaims(Iterable claims)
+ deleteExpenses(Iterable expenses)
```

**notes:**
- Since we do a lot of "by ID" it might seem appropriate to use hashtables. I found in assignment one that I was converting the hastable to a list to do almost every operation; and to be honest, I doubt there will ever be enough claims or expenses in a phone app to realize the run time gains of a hashtable over a list.    

- I know I've skipped tags, we would also need the methods for those I just didn't want that *sudo UML* to get too long

- We could also break the responsibility down further by having a ClaimManager, ItemManager, TagManager that the DataSource simply delegates to. (In-fact I think we should strongly consider this)

** These are all just ideas and my opinions, I'm very much open to criticism and other peoples ideas **

**Comment by TheLastBanana** [comment]
1.) Agreed. Hindle seems to use "listeners," but we should try to stay consistent with "observers."

2.) That sounds reasonable. We may also have controllers in the form of fragments or other helper classes that make up an activity.

3.) Looking at that link, it seems to me like a [parent-child relationship](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/parent-child.html) makes the most sense for our app. Everything we're describing is a one-to-many relationship.

4.) What kinds of advantages? I'm fine with doing it that way, just curious.

5.) Yeah, whatever way we go, we should remain consistent in how relationships are set up unless there's a very good reason not to.

6.) So in this situation, would we create an expense and then set its corresponding claim ID afterward? 

I used lists in the first assignment and it did simplify things a bit. That said, I wasn't using UUIDs. You're right that the performance almost definitely won't be an issue, but it still seems a little odd to constantly be iterating the list to get claims. Is there a reason we can't use a HashMap and just iterate its entrySet when necessary?

And I agree that breaking down the DataSource into delegate classes makes sense, especially if we're going to be storing each of those objects as separate documents.

**Comment by ryant26** [comment]
3.) Agreed

4.) [Elastic Search - Updating a Whole Document](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/update-doc.html#update-doc) tells us that when we need to update a document we actually replace it so if we delete an expense we need to rewrite the whole claim document to the server again as well as delete the item document. As oppose to simply deleting the item document. This principle is also true for our application side data. If we delete the expense item we are going to have to tell the claim to delete it out of it's list. That couples those classes a little tighter than if we just have the ID of the parent claim in the expense item.

6.) Yea, in whatever way we would have added the new expense to the list of expenses inside the claim we will just add the claim ID to the expense instead. 

Well for one, getting a single claim or expense seemed like the lesser used function. Typically I hand all of my expenses or all of my claims to a list adapter and then when you are clicking around in the list you are actually using the data in the list adapter not the data source. (Maybe this is a poor design though,  instead we could have our adapters delegate to the datasource, maybe then a hashtable makes sense?)

Second, when you request all the keys or all the values from a hashtable in java you get a set, which sucks to work with so you typically make an arraylist out of that. Seems like a lot of steps to me every time you want access to an iter-able or sort-able form of the keys or values (which was often for me).

Yea I think that is the way to go, Expenses, Claims, Tags, Users all get their own directory.

**Comment by TheLastBanana** [comment]
Good point about putting IDs on the "many" side. That's definitely the better choice.

I'm not terribly familiar with Java -- what makes sets suck to work with?

**Comment by kuzi117** [comment]
1-3: Yes.
4: The UML in the repo hasn't been updated since our first discussion. The one that was updated to include UUIDs was in my PR [here](https://github.com/kuzi117/TravelTracker/blob/4b87b35f49487bc5006feb16dcd19e76cfb75ac2/doc/data_model.png). I was considering merging just this in so that it included the UUIDs part but I've realized that it's mostly out of date since we're no longer wrapping the lists and it'll have to be updated again if we decide to do this UUID field in the Items.
5: Yes again.
6: So are you creating the Expense and then doing something like exp.setClaim(Claim)?

**Comment by ryant26** [comment]
@TheLastBanana 
Saying they suck to work with was probably extreme, they just don't fit our use case. They aren't index-able and they aren't sort-able. They just don't serve the same purpose as a list. But like I said before, it sort of depends on how we design our list adapters.   

@kuzi117 :
6. Yea, where the association happens isn't a big deal, it can be in the constructor or a setClaim or anything else that we decide.

**Comment by TheLastBanana** [comment]
Ah, yeah, I hadn't thought about the fact that sets aren't sortable. I guess we can use lists and refactor if we find any serious issues with it.

We should come to a decision soon on how our DataSource is going to work. We're pretty behind schedule as far as UML is concerned. I think the only remaining question is whether it'll be one class delegating to several manager classes, or several manager classes which delegate to the DataSource to do the actual saving and loading.

**Comment by ryant26** [comment]
What do you mean by saving and loading, from the server?

In any case I think the solution is still DataSource delegates to others.

**Comment by TheLastBanana** [comment]
It could be to the server. For now, it'll just be to a local file because we aren't integrating Elasticsearch until later.

**Comment by ryant26** [comment]
Yea the saving and loading should definitely be the responsibility of another class

**Comment by TheLastBanana** [comment]
So the way I'm understanding this is:
* One central DataSource class with methods as described in Ryan's earlier comment.
* Each of those functions delegates out to other classes to actually save and load. For example, getClaim and addClaim could delegate to a ClaimManager class.

If that's the case, why have a DataSource class at all? Aside from delegating to other classes, what does it actually do? The original reason for having it was that it would provide an interface by which we could load/save data which could be swapped out as we move from test data to local data to online data -- but at this point, it seems like that's all being handled by separate classes anyway.

**Comment by ryant26** [comment]
Yea, on second thought I think you're right. Splitting further into managers is unnecessary. But there is no way it can both manage the data and be responsible for loading and saving. I think it can be responsible for deciding when to load and save, but the actual process of loading and saving should be taken care of by another class.

**Comment by TheLastBanana** [comment]
That's why I suggested having the other classes delegate to DataSource rather than the other way around. ClaimManager handles Claim data, but when it needs to save or load, it talks to DataSource which is responsible for actually storing and retrieving data. Essentially, the DataSource acts as a filesystem.

**Comment by ryant26** [comment]
The problem will be that for Observer MVC to work well, you kind of need one main model class that the observers can watch.

**Comment by TheLastBanana** [comment]
Hm, fair enough. So our DataSource will hold all of the claims, items, tags, users, etc., but it can delegate to other classes to save and load the data.

**Comment by ryant26** [comment]
Yea exactly.

**Comment by kuzi117** [comment]
DataSource remains an interface though, correct?  What the DataSource delegates to is up to implementation. Or is that scrapped now.

**Comment by ryant26** [comment]
The way I see it, DataSource can be the interface or whatever DataSource delegates to for saving/loading can be the interface. I don't have a strong preference either way.

**Comment by kuzi117** [comment]
I figure it should be a single class implementing the interface that can delegate to others. So there will be a save to file class and a save to ES class at least that get delegated to by the DataSource

**Comment by ryant26** [comment]
Sounds good to me.

**Comment by kdbanman** [comment]
There's a lot going on here.  Here's the CRUD cycle I've distilled:

*Create*: Model objects are created directly from the model object classes.

*Read*: Model objects are retrieved from the DataSource by UUID.

*Update*:  Model objects are mutated using class interfaces (i.e. setters), and explicitly updated using the DataSource interface.

*Delete*:  Model objects are deleted by UUID.

```java
DataSource ds = DataSource.getInstance();  // Singleton dance

Claim selectedClaim = ds.getClaim(intentUUID);     // Read
Item item = new Item(selectedClaim);     // Create

// User plays with amount controller
item.setAmount(amt);     // Mutate

// IF user chooses "Save"
ds.newItem(item);     // Update

// ELSE user chooses "Cancel"
ds.deleteItem(item);     // Delete
```

**Comment by kdbanman** [comment]
Woop, I made an error above, fixing...

**Comment by TheLastBanana** [comment]
That sounds reasonable. The only issue I see is that we don't actually have a "save" button -- it's always saved as the user enters data.

**Comment by kuzi117** [comment]
I'm confused what `ds.newItem(item)` is actually doing. Is that writing data back to the DataSource?

**Comment by kdbanman** [comment]
@TheLastBanana , my mistake.  @kuzi117 , that's actually supposed to be `addExpense()` from @ryant26 's pseudo uml above.  Again, my mistake.

**Comment by kuzi117** [comment]
Oh, ok that makes sense, but it should be a combination of the two: `addItem()` to stay with the right vocab.

**Comment by kdbanman** [comment]
@kuzi117 , I agree.  That `ds.addExpense()` method taken together with our "save everything as it's edited" is a bit confusing to me, actually.  I'm going to state my assumptions, correct away:

- "saving" (to file, remote, or whatever the DataSource guts want) a model object **update** is done automatically when a setter is called.
- "saving" a model object **creation** is done explicitly with the DataSource adders, `ds.addItem()` for instance.

**Comment by TheLastBanana** [comment]
That makes sense to me. I think we shouldn't even be able to create an object outside of the DataSource. That way we can't accidentally create something but never save it.

**Comment by ryant26** [comment]
@TheLastBanana that's going to be challenging in code. What arguments would that method accept? how would we handle incomplete (or empty) fields?

**Comment by kdbanman** [comment]
@TheLastBanana, that's ringin' my bells.  Tell me what you think of this change to the pseudo UML interface:


`addClaim(Claim newClaim)`

changed to

`addClaim() : Claim newClaim`

The difference is subtle, but it means that the only way to add something to the model is to create it from the DataSource, Factory style.  That way adding things that are already instantiated / edited to the DataSource is impossible.

**Comment by kdbanman** [comment]
@ryant26, we replied at the same time.  Does the above answer your questions?  Or do I misinterpret you?

**Comment by ryant26** [comment]
@kdbanman Yea, that answered my question.

**Comment by TheLastBanana** [comment]
Yep, that's what I was thinking. Make the Claim constructor private so that they can only be created from the DataSource. Same deal with Item, Tag, User, and so on.

**Comment by kdbanman** [comment]
If it's private then it won't be accessible to the DataSource either.  You could make the constructors package protected and put the DataSource in the same package, though.

**Comment by kuzi117** [comment]
That's how I did things in my first project so I'm cool with that.
How about Items though?
```
Claim c = ds.addClain();
Item i = ds.addItem();
i.setClaim(c); // or i.setParent(c);
```

**Comment by kdbanman** [comment]
@kuzi117 what do you mean?  Like, how do we deal with setting Claim membership for a new Item?

**Comment by TheLastBanana** [comment]
Ah, my mistake. Meant to say protected.

@kuzi117 It makes sense to me to do this:

```
Claim c = ds.addClaim();
Item i = ds.addItem(c);
```

An item will only ever belong to one claim, and will never exist without that claim. So it makes sense to be part of its constructor (which in this case isn't really a constructor, but a method in the DataSource).

**Comment by kuzi117** [comment]
@kdbanman I really meant are we adding Items in the same way as claims. And then decided to add an example usage. Sorry for the confusion.

@TheLastBanana I suppose inside ds it still sets the item's parent though right?

**Comment by kdbanman** [comment]
I agree, @TheLastBanana .  The same problem exists for Claims as well - they belong to a User.

```java
Claim c = ds.addClaim(currentUser);
```

So then our UML is revised:

```
addClaim(User user) : Claim newClaim
addItem(Claim claim): Item newItem
addTag(User user): Tag tag
```

y/n?

**Comment by TheLastBanana** [comment]
That makes the most sense to me.

**Comment by kuzi117** [comment]
Works for me

**Comment by kdbanman** [comment]
Alright.  As for notifying the DataSource every time a setter is called, I asked @ryant26 a few days ago.  I liked his answer, so I hope I didn't misunderstand.

The DataSource could be registered as an observer to each model object.  The view objects are the intended model observers in Observer MVC, but I don't think we're abusing the system to do something like the following.  I know there's been discussion over whether or not DataSource is an interface, and how it relates to saving/loading.  Please critique:

```java
class DataSource {

  public Claim addClaim(User user) {
    Claim newClaim = new Claim();  // Claim internally generates UUID

    // ... delegate to whatever saver/loader was injected
    // in the DataSource constructor ...

    newClaim.addObserver(this);
    return newClaim;
  }

}
```

**Comment by TheLastBanana** [comment]
Yeah, that makes sense to me. One note: the user should also be passed to the Claim's constructor.

**Comment by kdbanman** [comment]
Thank you - edited.

**Comment by kdbanman** [comment]
@ryant26 and I were chatting a bunch.  There are some problems with the way I interpreted his description of Observer MVC.  If you're interested, the short version of the conversation is:

- observing individual model objects forces the model objects to either 1) inherit from some observable parent or 2) share repeated code
- option 1) above isn't bad, per se, but observing *lists* of model objects would require either 1) wrapping the lists in an observable class or 2) registering as an observer for each object in the list.
- option 1) is bad because of unclear separation between owner classes (User, Claim) and the classes that would wrap lists of Claims, Items, etc.

The alternative is what he originally meant, which would be used like this:

```java
class Claim(){
      
  public Claim() { ... };
  
  public void setDescription(String description) { 
    // ...
    Application.getDataSource.notifyDataUpdated();
  }	 
  
   public void setDate(...) { 
    // ...
    Application.getDataSource.notifyDataUpdated();
  }	 
  
   public void setDeblahblaah(...) { 
    // ...
    Application.getDataSource.notifyDataUpdated();
  }	 
  
}

class ClaimInfoActivity implements Observer {
  
  Claim claim;
  DataStore ds;
  Arraylist<Observers> observers;
  
  public onCreate() {
    ds = DataSource.getInstance();
    
    UUID claimId = getIDFromIntent();
    claim = ds.getClaim(claimID);
    
    ds.addObserver(this)
    
    updateViews();
  }
  
  @override
  void updateObserver(){
   	updateViews(); 
  }
  
}
```

Note that:

1. The DataStore is observed, not the model objects.
2. The model object (Claim) is no longer tightly coupled by inheritance just for observability.

We'll turn this issue's comment thread into some UML tomorrow.  I'm pretty thankful to be in a group that'll discuss this kind of stuff so extensively.

**Comment by TheLastBanana** [comment]
That sounds good to me!

**Comment by kdbanman** [comment]
Server interface and datastore UML are now complete.  Once @kuzi117 's PR is updated re: it's review, then merged, P3 UML will be done!

**Comment by kuzi117** [comment]
Wait, we're still merging my PR? I was under the impression that @ryant26's commit had everything my PR did.

**Comment by TheLastBanana** [comment]
We're going to keep the UML you added, but not the rest.

**Comment by kuzi117** [comment]
Can we selectively exclude bits of the PR? Also, I need to remove the note about the lists being wrapped.

**Comment by TheLastBanana** [comment]
I'm not sure. It might be easier to just open a separate PR.

**Comment by ryant26** [comment]
git checkout source_branch <paths>

will pull specific files into your branch

**Comment by TheLastBanana** [comment]
Thanks. I went ahead and did that. @kuzi117, if you want to make any changes, go ahead and do that and then close this issue.

**Comment by kuzi117** [comment]
Closing this issue, I made the changes and we've handed in.
