### ISSUE TITLE
Skeleton code for offline portion of model

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#25]
This should include at least classes and method stubs. Some code can probably be reused from our solo assignments.

**Comment by kdbanman** [comment]
If "skeletal" means attributes and methods from the UML, we are nearly done.  These have yet to be skeletoned fully:

- DataSource
- Cache
- ServerInterface (probably not necessary at this point, really)
- ResultCallback

**Comment by kuzi117** [comment]
How's this looking guys? It's due today.

**Comment by kdbanman** [comment]
I just finished that shell I was writing.  I'll get on this tomorrow.
