### ISSUE TITLE
Test fixture for Elasticsearch

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#26]
We should have an interface in place which "pretends" to be ElasticSearch, but actually just stores files locally.

**Comment by kdbanman** [comment]
'DummyDataSource` class has been started for this purpose.  #60 should be resolved before moving too far forward, though.

**Comment by TheLastBanana** [comment]
InMemoryDataStore is implemented. We'll need a version to store files locally, but it's a less pressing issue for now.
