### ISSUE TITLE
Implement UC.SubmitExpenseClaim

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#28]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#ucsubmitexpenseclaim)

**Comment by therabidsquirel** [comment]
This is kind of wonky right now. A couple problems:
- Click the submit button on a claim and getting the error that not all expense items are complete. View expense items and mark all of them as complete. Go back to ClaimInfo, and as soon as it pops up the claim status is now submitted without having to hit the button again. Not sure why that's happening.
- The activity probably needs to restart upon submitting, or just close, as listeners for editing are still present. Currently you can edit the dates either way, which is it's own issue, but destinations are set to only be editable when the claim is In Progress or Returned.
- Submitting a claim doesn't change the status right away. You have to navigate to another view and then back for it to update. As per my previous point, submitting a claim should probably restart the activity or close it taking the user back to ClaimsList.
- You can submit an Approved claim. You can also submit a Submitted claim, which obviously has no effect, but perhaps there should be a message or something upon trying to submit an already submitted claim?

**Comment by kdbanman** [comment]
Thanks for pointing those out.  I was aware of a couple of those
points already - I'm not exactly sure why I closed the issue on that commit
knowing there were problems.

**Comment by therabidsquirel** [comment]
Also, looking at [this forum post](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=480482), we might want to check for incomplete fields before submitting as well.

I can't really think of incomplete fields though.
- Dates are (or probably should be) set to the current date by default.
- Not having destinations shouldn't matter, nor should not having item descriptions or receipt photos.
- The amount on items maybe.
- Neither our currency or category spinners have any kind of no option, so even though both are set to null I think for new items, the spinners in the UI can't indicate that. If we just set them to defaults, then they can't be "empty".

He also mentions that a user might be able to submit the claim anyway as long as they are prompted with a dialog (yay!) warning them of incompleteness, though I feel that's more of something we could decide to do or not.

**Comment by therabidsquirel** [comment]
Also just remembered that according to the UI diagram the user is being prompted with a confirmation dialog if they hit the submit/return/approve button. We can change the diagram if we just want to submit/return/approve without confirmation as the respective button is hit, though I personally think asking for confirmation is a good idea.

**Comment by kdbanman** [comment]
I agree, the confirmation will be there.

**Comment by kdbanman** [comment]
I wonder if there's a way to reference a commit without the `closes #XX` string...

**Comment by kdbanman** [comment]
closed by #88, #89, #90, #91
