### ISSUE TITLE
Implement Use Case UC.CreateExpenseClaim

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#3]
Implement [this use case.](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#uccreateexpenseclaim)

**Comment by ryant26** [comment]
My vote is autofill, uneditable. Then mark the editable field as an enhancement that would require like an account settings page to edit that info.

**Comment by kdbanman** [comment]
I think you're right.  My hunch is that we can treat Users as immutable things retrieved from the server.  We'll know when the TA replies to that questions email.
