### ISSUE TITLE
Implement UC.FilterClaimsByTag

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#32]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#ucfilterclaimsbytag)

**Comment by TheLastBanana** [comment]
Ryan and I are swapping places on this one -- he's going to take over on backfilling test cases, and I'm going to implement this.

**Comment by TheLastBanana** [comment]
Closed by df7a2483843fb52d7ba99fd3da97e2b8e4b4e739.
