### ISSUE TITLE
Implement UC.ManageTags

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#33]
Implement [this use case](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Use-Cases#ucmanagetags)

**Comment by kuzi117** [comment]
As I'm understanding, this UC is just to view the tags?

**Comment by TheLastBanana** [comment]
It is, yeah. The other tag behavior is covered by other issues (UC.CreateTag, UC.DeleteTag, and so on).

**Comment by kuzi117** [comment]
Closed in 232651782de2024409ecff814f63bb449bca3f0b
