### ISSUE TITLE
Style Guide Question

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#40]
In Android, that I know of at least, there are two ways to get clicking a button to do something, and that's either having it call a method specified in the xml or creating the appropriate listener in the activity. I think it's very important we pick one and stick with it, and I think that listeners are the better way to go for organization and readability.

**Comment by ryant26** [comment]
I agree 100%

**Comment by kdbanman** [comment]
> I think it's very important we pick one and stick with it

Yep.

> listeners are the better way to go for organization and readability.

Yep.  Behavior and presentation should be as separate as possible.  Having `onClick` callbacks registered in our layout xml pretty directly violates that principle.

**Comment by TheLastBanana** [comment]
Agreed. Listeners are best.

**Comment by kuzi117** [comment]
Closed and pushed to the [wiki](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Style-Guide)
