### ISSUE TITLE
Another style guide question.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#41]
View IDs in our layout xml files are a point of concern for me.  Every ID for every view in every layout file gets slammed into the global `R.id` namespace.  For this reason, I think we need to manually namespace our view IDs.

For example, take the claim info activity, where we're looking at an individual claim in detail.  There are a two files:

- ClaimInfoActivity.java
- ClaimInfoLayout.xml

Prefixing each component's ID in the layout with `ClaimInfo` is what I did for assignment 1.  Rather than a `TextView` called `UserName`, I would give it the ID `ClaimInfoUserName`.  This prevented view ID collisions and made autocomplete on `R.id.*` actually useful.

Thoughts?

**Comment by kuzi117** [comment]
I never considered it before but I like it.

**Comment by therabidsquirel** [comment]
I like it too.

**Comment by TheLastBanana** [comment]
Sounds good to me.

**Comment by kuzi117** [comment]
Closed and pushed to the [wiki](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Style-Guide)

**Comment by TheLastBanana** [comment]
Three points of clarification:
- Camel case or Pascal case, e.g. `claimInfoDescription` or `ClaimInfoDescription`?
- Should we include the view's type as a suffix, e.g. `ClaimInfoDescriptionEditText` or just `ClaimInfoDescription`?
- Should we include the word "Activity" in the activity name, e.g. `ClaimInfoActivityDescription` or `ClaimInfoDescription`?

**Comment by therabidsquirel** [comment]
My feeling is the same as yours on all three.

**Comment by kdbanman** [comment]
Ditto, those are perfect for me

**Comment by ryant26** [comment]
First two are good with me.

I kind of like having "activity" in activity names (usually at the end) ```ClaimInfoDescriptionActivity``` but I'm not married to it if everyone else prefers otherwise. IMO ClaimInfoDescription could be a class that handles the formatting / style / other properties of a Claim Info Description, but having the activity makes it a bit more clear

**Comment by TheLastBanana** [comment]
@ryant26: I'm specifically referring to view IDs. The activity name would still be ClaimInfoDescriptionActivity, but its view IDs would only be prefixed by ClaimInfoDescription since we can infer that if it's an ID, it's embedded in an activity.

**Comment by ryant26** [comment]
@TheLastBanana Oh, my mistake. Then yes I agree.

**Comment by kuzi117** [comment]
Updated [wiki](https://github.com/CMPUT301W15T07/TravelTracker/wiki/Style-Guide).
