### ISSUE TITLE
Create Glossary Terms

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#5]
We need a glossary.

It's mostly done, but @TheLastBanana will post a link and close the issue when it's complete.

**Comment by TheLastBanana** [comment]
Here's the wiki page. Everyone, please take a look when you get a chance and let me know if you think anything is missing or needs to be changed.

https://github.com/CMPUT301W15T07/TravelTracker/wiki/Glossary

**Comment by kuzi117** [comment]
Checking in, I'm sort of biased since I helped make it, but I don't know what else we need to add. So as far as I'm concerned I'm good.

**Comment by kdbanman** [comment]
I'm perfectly happy if that gets submitted as part of our deliverable.  If you notice anyone not obeying the glossary terms in code, requirements, or whatever, please yell as loudly and violently as possible.

**Comment by TheLastBanana** [comment]
Everyone seems happy with the glossary, so I'm closing this.
