### ISSUE TITLE
Create claim list layout

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#50]
Refer to the UI diagram:
![UI diagram](https://raw.githubusercontent.com/CMPUT301W15T07/TravelTracker/master/doc/UI_diagram.png)

**Comment by ryant26** [comment]
[commit](https://github.com/CMPUT301W15T07/TravelTracker/commit/18bddf136e76849c3074caf9e3d4eb6b4a530642)
