### ISSUE TITLE
Create claim info layout

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#52]
Refer to the UI diagram:
![UI diagram](https://raw.githubusercontent.com/CMPUT301W15T07/TravelTracker/master/doc/UI_diagram.png)

**Comment by therabidsquirel** [comment]
So I've been thinking about how to implement this. Given the amount of information that needs to be displayed, it would be nice to have the entire screen scrollable somehow like with a listview. I don't think a listview would work though, as you'd have very different elements, some that can be edited and some that can't too. I don't think an element in a listview knows anything about any of the other elements either.

So I'm stuck. I've pushed my most recent changes on this layout. Experimenting I tried seeing what it would look like to put in everything as separate listviews and buttons and textviews and whatnot, but as you can see for yourself the screen gets crowded way too quickly without some way to scroll through what I have. I've tried Googling, but apparently this is a hard thing to do? Anyone with more Android know-how have any ideas or solutions?

**Comment by ryant26** [comment]
Maybe I'm misunderstanding the issue, but did you look into using a ScrollView?

**Comment by therabidsquirel** [comment]
No, that doesn't seem to be capable of it. I drew up a quick picture to represent the problem. With a limited screen size, is it possible to scroll through a bunch of various buttons and views and whatnot?

![diagram1](https://cloud.githubusercontent.com/assets/6912794/6433497/f77ce2a2-c02d-11e4-84ad-7e21c5f18b48.png)

**Comment by kuzi117** [comment]
Yes, ScrollView should let you.

**Comment by therabidsquirel** [comment]
This is a total dumb moment, but I just realised by placing objects below the screen it extends it. Problem solved now. XD

**Comment by skwidz** [comment]
Scrollview would be ideal, but you cant use listveiws with it (according to the scrollveiw documentation)
Some solutions that i can think of: 
-Make your listveiws smaller  to fit everything on one screen
-ditch the listveiws and have a fragment listveiw for veiwing the lists that would come up from descriptive button
-say fuck it and put the listviews in the scrollview anyway.

**Comment by therabidsquirel** [comment]
You can have a relative layout inside a scollview, and that will do it I believe.

**Comment by therabidsquirel** [comment]
It auto-generated the scrollview with a linear layout inside it, and I was able to put a listview in the linear layout.

**Comment by therabidsquirel** [comment]
Closed by d54e2c6.
