### ISSUE TITLE
Final DataSource design change.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#55]
This should be the last time we have to talk about this.

Yesterday we figured out that we can use multiple Application classes to do dependency injection.  See snippets below.  DataSource no longer needs to be a proper singleton with DataSource.getInstance() - it should actually be an Interface.  Our first implementation of DataSource would be a DummyDataSource that just does everything in memory - no files, no elasticsearch, maybe not even adding data (just hard coded defaults).  Luckily it'll only be a small change to the datasource uml at this point since we have no code.

```java
class TravelTrackerApp extends Application {
  private DataSource ds;  // never changes!
  public DataSource getDataSource() {  return ds; }
}
```

```java
class DummyApp extends TraverTrackerApp {
  public void onCreate() {
    ds = new DummyDataSource();
  }
}
```

```java
class ProductionApp extends TraverTrackerApp {
  public void onCreate() {
    ds = new ElasticSearchDataSource();
  }
}
```

Objections? Critiques?

**Comment by TheLastBanana** [comment]
That looks good to me. Hopefully this will let us test easily.

**Comment by kdbanman** [comment]
I haven't fully researched this, but we might need our different Application classes to inherit from [`MockApplication`](http://developer.android.com/reference/android/test/mock/MockApplication.html) for testing purposes.  If this is the case, then we probably have only one *actual* TravelTracker Application, and as the project progresses we would just change the `ds = new WhateverDataSource()` line in that actual Application.

That's still compatible with the above - the key is that DataSource is an interface that we implement in different ways.

**Comment by ryant26** [comment]
@kdbanman Thats the way I envisioned it. Dependency injection is only possible in the testing environment where we can inject mock applications. In the main source it cant be injected. I don't think that will cause an issue for us.

**Comment by kdbanman** [comment]
:+1:
