### ISSUE TITLE
Model objects do not currently notify DataSource of changes within setters.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#60]
Not sure how to address this, so this is an RFC.

Our `DataSource`s have a `public void notifyDataChanged()` which should be called within model objects (`Document`s specifically).  The idea is that when a `Document` changes, the `DataSource` should know so it can push to the server, or cache the dirty ones to a file, or whatever.

Having the existing `notifyDataChanged()` is one way to do it, but we would need to change `Document` to have a `DataSource` attribute, and subclasses of `Document` would need to call the notify method within each setter.

Alternatively, `Document` could inherit from `Observable`, and call `updateObservers()` within each setter.  `DataSource` would implement the `Observer` interface and add itself as an observer to each `Document` it returns.  I prefer the latter, since Document would not be coupled to DataSource.  Here's a usage example:

```java
public class DummyDataSource extends Observable<DummyDataSource> implements DataSource, Observer {

	private Collection<Claim> claims;
	private Collection<User> users;
	private Collection<Item> items;
	private Collection<Tag> tags;
	
	@Override
	public void addClaim(User user, ResultCallback<Claim> callback) {
		Claim claim = new Claim(UUID.randomUUID());
		
		// TODO associate claim with user
		
		claim.addObserver(this);  // <---- here is the magic line
		
		callback.onResult(claim);
	}
```

**Comment by ryant26** [comment]
I think we already ruled out observer pattern for model objects like the Documents. 

The notifyDataChanged() doesn't have to go in the setters for those model objects. There is going to have to be some method in the activities that takes the updated text entry fields and puts them into the model object. Since the activity will already have a reference to DataSource, the activity can call notifyDataChanged() after it makes a change to a model object.

**Comment by TheLastBanana** [comment]
My only concern with notifyDataChanged() being called from the Activity is that it moves away from active-model MVC, which seems to be what we're expected to use.

**Comment by ryant26** [comment]
@TheLastBanana you are right about that. Do you have an alternative in mind or do you prefer the observer pattern that @kdbanman suggested?

**Comment by TheLastBanana** [comment]
Ideally, I would probably do what you suggested. But given the course expectations, I think something like @kdbanman's observer pattern is our best bet.

**Comment by ryant26** [comment]
If we are confined within the active mvc model and cannot deviate then I think the observer pattern is the way to go as well.

**Comment by kdbanman** [comment]
> I think we already ruled out observer pattern for model objects like the Documents.

Sorry I misunderstood that - I thought we ruled out activities/views observing model objects, not the DataSource itself.

> Since the activity will already have a reference to DataSource, the activity can call notifyDataChanged() after it makes a change to a model object.

The active model problem is my concern.  I just asked for clarification on the class forum about whether or not we're confined to active model MVC.

Something to watch out for with the observer pattern I described is that the DataSource doesn't know anything about non-Document model objects.  Destination, ApproverComment, and Receipt are the ones I'm talking about.  They're not just simple enums, and they are not CRUDded by DataSource.  Hence, the DataSource has no place to add itself as an observer to them.

For example, if we were to call `setPhoto(...)` on a Receipt object of an Item, the DataSource wouldn't get notified because the Item itself isn't mutated.  The way I suggest dealing with that is not having setters on the non-Document objects.  To change them, reconstruct them and use the setters on the Document objects.  Then every change is observable by the DataSource.

**Comment by kdbanman** [comment]
We could call `addObserver()` within the Document objects, too.  It'd look like this:

```java
class Item extends Document {    // Document extends Observable
  // ...

  @Override    
  public void addObserver(Observer obs) {
    super.addObserver(obs);

    // need to override addObserver and add obs to each non-Document attribute
    if (this.receipt != null) this.receipt.addObserver(obs);  
  }

  public void setReceipt(Receipt receipt) {
    if (this.receipt != receipt) {
      this.receipt = receipt;

      // also need to add observers to any new non-Document attribute
      this.receipt.addObservers(this.observers);
    }
  }

  // ...
}
```

**Comment by TheLastBanana** [comment]
It comes down to whether or not we think we'll need to mutate objects that are contained within Documents. At the moment, all of those objects could easily be re-created if we're changing them. Do we anticipate that changing? If we do, we should probably just add observers to them.

**Comment by kdbanman** [comment]
> At the moment, all of those objects could easily be re-created if we're changing them. Do we anticipate that changing?

Where do you believe the threshold lies for "too complex to recreate instead of using setters"?

**Comment by kdbanman** [comment]
I'm going to implement the "only Documents are observers, recreate every non-Document" option.

From a maintenance perspective, if we change our minds later need to switch, none of our code will break by adding observers.  But if we *start* with observers everywhere, then things could break if we move to a recreation pattern.

Besides, it's a less complex change from what we have right now :-)
