### ISSUE TITLE
Enum strings should refer to values in strings.xml

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#61]
E.g. instead of "In Progress," use R.string.in_progress.

**Comment by kdbanman** [comment]
Neat.  I didn't think of this.

**Comment by TheLastBanana** [comment]
One consideration though: that will give us an ID rather than a string. To get the actual string, we need to call context.getString(id).

**Comment by TheLastBanana** [comment]
Now that I look at this a little more, this would require us to remove the toString function from enums because they don't know what context they're in. Is that worth it?

**Comment by kdbanman** [comment]
Hmm.  Perhaps not.  After thinkng about it, strings.XML is mostly for UI maintainability and internationalization.  I suppose enum string representation will be directly shown to the user though...

What do you mean by context?

**Comment by TheLastBanana** [comment]
We can't retrieve a string from its ID value without [`Context.getString(id)`](http://developer.android.com/reference/android/content/Context.html#getString(int)). A raw enum doesn't have access to a Context, however.

**Comment by therabidsquirel** [comment]
We would be able to make a toString method that takes a context argument, though that would no longer be an override of toString then, which may or may not be a problem? Depending on whether something is automatically calling toString methods or not.

strings.xml is mostly for UI stuff I believe. It'd be nice to put all the enum strings into it, but I'm not sure the approach to doing so is clean enough for my liking. I don't really like taking toString out of the enums, but I don't really like making one that takes a context either.

**Comment by TheLastBanana** [comment]
The problem is that several of our enum strings are going to go straight to the UI. For example "In Progress" or "Submitted" will show up in the UI, so it follows that they should probably be in strings.xml.

**Comment by therabidsquirel** [comment]
True, did not fully think of it like that. With that in mind I think we should make it so the enum strings are in strings.xml. I think having a toString method in the enums that takes a context would work best, unless there's a problem with that I'm not seeing.

**Comment by kdbanman** [comment]
I don't know much about how the context system works, but it should be fine to have a `toString` that uses a context or something to resolve strings at runtime.

In order to make each enum play nice with a generic spinner adapter, they will have to implement a common interface, like `ContextStringable`  Note the `TODO` comment:

```java
public interface ContextStringable {
      public String getString(Context ctx);
}

public enum Status implements ContextStringable {
	IN_PROGRESS,
	SUBMITTED,
	RETURNED,
	APPROVED;
	
	@Override
	public String getString(Context ctx) {
		// TODO: how would this look??  keep in mind we can constructors and attributes for each enumeration if we need to reference them somehow
	}
}
```

**Comment by therabidsquirel** [comment]
I believe it would look something like this:

```java
public enum Status implements ContextStringable {
    IN_PROGRESS(R.string.enum_status_in_progress),
    SUBMITTED(R.string.enum_status_submitted),
    RETURNED(R.string.enum_status_returned),
    APPROVED(R.string.enum_status_approved);

    private final int id;

    private Status(int id) {
        this.id = id;
    }

    @Override
    public String getString(Context context) {
        return context.getString(id);
    }
}

**Comment by kdbanman** [comment]
Neato.  Looks pretty straightforward.

**Comment by therabidsquirel** [comment]
I can implement this for all our enums if we're all in agreement about it.

Also, shit. Was playing around with assignees on issues, and now you all can see. XD

**Comment by TheLastBanana** [comment]
Please do! That would be great.
