### ISSUE TITLE
Implement and test InMemoryDataSource

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#65]

**Comment by TheLastBanana** [comment]
Sorry for the delay on this. I've been busy with other projects, and as usual, the unit testing is taking some unexpected twists.

Since our DataSource accesses are all asynchronous, I needed to write some  wrapper code around ResponseCallback to synchronize to the test thread. It'll be very useful for testing other classes in the future.

I'll finish this up and push it tomorrow.

**Comment by kdbanman** [comment]
+1  This is a good thing to have finished.
