### ISSUE TITLE
User role as an Enum and as a class hieranchy is redundant.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#66]
I notice we now have a `UserRole` enum in the model for approver or claimant states.

IIRC, this was for passing around role state between activities using intents.  This kinda reflects the argument I was making earlier - it's cleaner to model user role with an enum rather than a class heirarchy.  Because approvers and claimants can literally be the same person/user, user role is actually an application state.

I'd be happy to make the necessary changes to the UML and model.

**Comment by therabidsquirel** [comment]
This is why I'm for a UserRole enum, because user role is more of an application state than anything else.

**Comment by TheLastBanana** [comment]
Yeah, I think an enum makes more sense for how we've designed our app.

**Comment by kuzi117** [comment]
We should get this done, so we don't continue with weird state. @kdbanman doing it, or I can?

**Comment by kdbanman** [comment]
I'm on it.
