### ISSUE TITLE
No data loss does not play nicely with "undoable" model changes.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#67]
(Moving this from slack because that makes sense.)

I spoke to :hindle: after class, our app should *not* lose partially entered data, so save/cancel prompting on activity navigation is not an option.

### Option 1 (easy)

No undo / change cancellation.  User made a change --> User may be sad if (s)he did not mean to do that.

### Option 2 (hard)

Our prompting mechanism was a way to allow the user to cancel changes, which is an important feature.  We should discuss ways to have no data loss and change cancelation, but we may have to throw away change cancelation if we can't make it feasible.

My proposal: I think we can combine saving on every keypress and cancelling changes with a prompt on navigation.  Our Documents are already stored locally with mutations using a `dirty` flag attribute.  Dirty Documents are GSONed to a local file if we don't have connectivity, and DataSource preferentially CRUDs with those local dirty documents, syncing with the server when it's possible/sensible.  @ryan, this is your domain - lemme know if I misunderstand.

Rather than a simple `dirty` flag, Documents could have a few states: `clean`, `edited`, `confirmed`, or `cancelled`, and the DataSource (actually, the Cache backend the DataSource is interfacing with) deals with the Documents accordingly.  See the state diagram below.

![State Diagram](https://slack-files.com/files-tmb/T03J3S54U-F03T6KS8D-ae7df30c7c/img_20150363_114055_1024.png)

**Comment by ryant26** [comment]
Now that we are constrained further (we have to save partial entries), the undo becomes a "nice to have" feature that requires *a lot* of refactoring if we decide we want it down the line instead of right now. 

Although I was initially a strong advocate for undo I'm not sure it's worth the fuss of creating this document state machine. Unless someone comments with a compelling argument I'm going to throw my vote on option 1

**Comment by kdbanman** [comment]
To be clear, I actually prefer option 1 as well.  It was fun to think about that document state machine thing, but it'd be a lot of work to implement and even more to test properly.  The bugs that would come out of small problems from that system would be a headache, too.

Before we completely rule it out, though, perhaps we should make a forum post specifically asking about undoable changes with an explicit example?

**Comment by therabidsquirel** [comment]
We could make a forum post. I'm with you two in that unless someone has a really good argument for option 2, option 1 will be a lot less work and still satisfy requirements.

**Comment by skwidz** [comment]
I'm for option one. If the undo feature isn't a requirement then I don't think we need to implement it, especially if it's going to create a big headache

**Comment by TheLastBanana** [comment]
I'm also for option one.

**Comment by kdbanman** [comment]
I made the forum post.  As long as we don't have to support undo, option 1 is go!

**Comment by kdbanman** [comment]
Hindle replied.

Change cancellation is officially a nice-to-have.  All changes can be made in place with no concept of history.  **Can anyone think of any necessary changes to the docs to reflect this?**  I'm pretty sure all the UML and the Use Cases are clean.  What about UI diagrams?

**Comment by TheLastBanana** [comment]
The UI diagrams should be fine. They were written before we'd considered undo, so they have no references to undoing.

**Comment by kdbanman** [comment]
Nifty.

**Comment by therabidsquirel** [comment]
Being the one who's done most of the maintenance on the UI diagram, I can confirm there's no reference to undo.

**Comment by kdbanman** [comment]
:+1:
