### ISSUE TITLE
User Interface Mockup

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#7]
"Diagram the layout of your main user interface and major dialogs, with comments describing the important elements."
We need the initial interface mockup added to the wiki.

**Comment by kdbanman** [comment]
does anyone see screens or buttons missing from [this](https://github.com/CMPUT301W15T07/TravelTracker/blob/master/doc/Storyboard301.png)?

If not, we should pop it in the wiki and close this issue.
