### ISSUE TITLE
DataSource deletion methods should be parametrized by void.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#71]
Currently `DataSource` delete operations take a `ResultCallback` that is parametrized by the type that is deleted.  This is misleading, because the object is gone - manipulations are no longer meaningful.  Instead, they should take a `ResultCallback<Void>`

**Comment by TheLastBanana** [comment]
This is a pretty quick change. I'm going to implement it now since I need it working to handle test cases properly.
