### ISSUE TITLE
Add LinearLayout listed Claim info

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#73]
E.g. claimInfoDestinationsLinearLayout, claimInfoCommentsLinearLayout.

**Comment by therabidsquirel** [comment]
Destinations are fully done. Tags will wait till Part 5. Comments I can do as a LinearLayout, having spent something like 13 hours on the destinations LinearLayout.

@kdbanman You mentioned you would switch the comments from the nonScrollListView back to a LinearLayout. I can take care of this and remove the nonScrollListView, I just want to be sure you aren't/haven't already done any of that so I don't mess with stuff.
