### ISSUE TITLE
Using Context Menu for Claim Deletion Instead of Dialog

### ISSUE THREAD

**Issue by ryant26** [CMPUT301W15T07/TravelTracker#78]
I would rather use a context menu to do the deletion of claims from the list rather than a pop up. I think it looks cleaner and feels more modern. I implemented this in the first assignment you can see how that looks:

https://archive.org/details/ThornhilTravelExpensesFinal @ 1:55

In that case I used an "X" for delete but I would use a trash can this time (from the stock icons). I wanted to see what the thoughts were on this, especially from @therabidsquirel since he worked so hard on designing the UI.

**Comment by therabidsquirel** [comment]
I do like the look of that better. Couple questions though:
- Is that context menu being brought up when you long-click on a claim/item, while a short-click is taking you to the view screen?
- In the video deletion was with the "X", and you suggest replacing that with a trash can (which I like). Was the check mark in the video cancel? Whatever it was, is there something you want to replace it with for our project?

**Comment by ryant26** [comment]
- Yes, the long click brings up the context menu, while short still take you to the view activity
- Yes, the checkmark was cancel. That is confusing though, I'm thinking maybe the android back arrow "<" ? Do you have another suggestion for this?

**Comment by therabidsquirel** [comment]
Yeah, that is confusing to have a checkmark as cancel. XD Using a trash can icon as delete definitely leaves no room for ambiguity. A back arrow could work as cancel, but I feel I've seen something in apps that looks better. I can't currently recall though, and I'm looking through apps on my phone to see what they do.

**Comment by therabidsquirel** [comment]
I feel like a back arrow implies navigation of some kind, whereas you're not changing activities or even in any kind of dialog. Maybe a trash can for delete and an "X" for cancel?

**Comment by ryant26** [comment]
Undo arrow:
![ic_action_undo](https://cloud.githubusercontent.com/assets/3953165/6629763/379cf514-c8d7-11e4-990c-d4d4270359f5.png)

Cancel:
![ic_action_cancel](https://cloud.githubusercontent.com/assets/3953165/6629772/4f33943a-c8d7-11e4-90e6-44d7ad3eb498.png)

Back:
![ic_action_back](https://cloud.githubusercontent.com/assets/3953165/6629776/60c3e588-c8d7-11e4-8d8b-419d5c20aab3.png)

Any of these do it for you?

**Comment by therabidsquirel** [comment]
I feel kind of like the "X" to cancel? But then if you're trying to cancel a delete, you might no be so tempted to hit and "X". I dunno, what do you think?

**Comment by ryant26** [comment]
Thats my thought too, android calls it "cancel" but I wouldn't really feel comfortable using an x when selecting something like a claim. The "keep" ( android note writing app) uses the "back" arrow for cancelling the context menu

**Comment by therabidsquirel** [comment]
I feel like using the back arrow (the third one) is probably our best bet.

**Comment by ryant26** [comment]
All right, let it be known. The back arrow is the choice!

**Comment by therabidsquirel** [comment]
I'll update the UI for long-clicking in ClaimsList and ExpenseItemsList.

**Comment by ryant26** [comment]
All right, lets tag the person who is doing expense list so they know it has been changed. @kuzi117

**Comment by therabidsquirel** [comment]
UI updated in 7cf4783.
