### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#79]
Add any notes as comments. If you've solved the issue, use strikethrough (`~~text~~`) to indicate that it's been addressed.

**Comment by TheLastBanana** [comment]
**General:**
- We should probably standardize what to do with errors. I've just been making a toast with the message.
- I notice that a lot of our nested classes are using PascalCase for naming rather than camelCase. Is this something we want to stick with? It seems inconsistent with our class naming scheme.

**activity.ClaimInfoActivity**
- Some callback methods should be split out into nested classes as per our style guide.

**activity.ClaimsListActivity**
- [Line 129](https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/activity/ClaimsListActivity.java#L129) - is there a better way to handle this? This is going to cause us headaches with dependency injection.

**activity.TravelTrackerActivity.java**
- Missing documentation for `loadedLatch`, `app`, and `datasource`.

**Most classes in model package**
- Missing documentation for most methods.

**model.ApproverComment**
- Missing license.

**model.ItemCurrency, model.ItemCategory, model.Status, model.UserRole**
- Inconsistent indentation in `fromString()` method.

**serverinterface.Cache, ResultCallback, ServerHelper, ServerOperation**
- Missing class-level documentation.

**serverinterface.MultiCallback**
- Some callback methods should be split out into nested classes as per our style guide.

**util.ClaimAdapter**
- Missing class-level documentation.
- Missing license.

**util.ClaimsListDataHelper**
- Missing class-level documentation.
- Missing license.
- Missing most function documentation

**util.ClaimUtilities**
- Missing class-level documentation.

**util.MultiSelectListener**
- Inconsistent license (I'm assuming this was pulled from existing code).
- Missing class-level documentation.

**util.NonScrollListView**
- Missing license.
- Missing class-level documentation.

**util.Observable**
- Missing class-level documentation.

**Comment by ryant26** [comment]
@TheLastBanana 
> activity.ClaimsListActivity
> Line 129 - is there a better way to handle this? This is going to cause us headaches with dependency
> injection.

The reason for that line is this:
```java
public class InMemoryDataSource extends Observable<InMemoryDataSource>
```
InMemoryDataSource should be declared as the following:

```java
public class InMemoryDataSource extends Observable<DataSource>
```
I can re-factor that and see if it breaks anything, then I will fix what I have done

**Comment by kdbanman** [comment]
### ExpenseItemInfoActivity

- in `populateExpenseInfo(Item item)`, there are many silently swallowed `NullPointerExceptions`.  Expected control flow should not be directed by exception handling.  Null references should be explicitly checked with `== null`, and messages should probably be toasted in most cases.

**Comment by therabidsquirel** [comment]
I added all missing licenses and consistently formatted them in 6ff7d27. There's likely more things we want to cover by now, but here's @TheLastBanana's list from March 13 updated:

**General:**
- We should probably standardize what to do with errors. I've just been making a toast with the message.
- I notice that a lot of our nested classes are using PascalCase for naming rather than camelCase. Is this something we want to stick with? It seems inconsistent with our class naming scheme.

**util.ClaimsListDataHelper**
- Missing most function documentation

**util.MultiSelectListener**
- Missing class-level documentation.

**Comment by kuzi117** [comment]
Are nested classes supposed to be camelCased? I thought all classes anywhere were PascalCase. If they're camel then I'm a a perpetrator of evil things.

**Comment by TheLastBanana** [comment]
Whoops, that comment was supposed to be the other way around. We have a mix of both, but I'd prefer PascalCase (and I believe it fits our style guide).

**Comment by kdbanman** [comment]
Ha woops. After reading that comment I made a couple camelCased nested
classes.

**Comment by TheLastBanana** [comment]
I went through and tried to fix up warnings and TODOs. I ignored anything relating to cache/server-side things or tests because those are still under construction.

**Things marked as TODO:**
- https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/activity/ExpenseItemInfoActivity.java#L565
- https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/activity/ExpenseItemsListActivity.java#L250
- https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/model/Receipt.java#L45
- https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/util/ClaimAdapter.java#L150
- https://github.com/CMPUT301W15T07/TravelTracker/blob/master/src/cmput301w15t07/TravelTracker/util/MultiSelectListener.java#L51

If you committed one of these TODOs, please take a look and either remove them or address them.

**Comment by kdbanman** [comment]
thanks for ignoring the caching ones.

**Comment by therabidsquirel** [comment]
The code is as reviewed as it's gonna be. I do know every file has a license at the start though. Closing this.
