### ISSUE TITLE
Anonymous classes with captured data

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#80]
According to our style guide, an anonymous class of over 5 lines or more than 1 method should be turned into a nested class. What about cases where the anonymous class is used to capture variables scoped only to the function which creates it?

For example, consider [the current MultiCallback implementation of `createCallback()`](https://github.com/CMPUT301W15T07/TravelTracker/blob/7b705ede9a4b8e95ad1f8314288a7872b232bd69/src/cmput301w15t07/TravelTracker/serverinterface/MultiCallback.java#L68-L99). The variable `id` is captured by the anonymous callback class. If it were to be split out into a nested class, it would need to be passed as an argument to the new class. This is a simple example, but there are likely other cases we haven't run into yet that will require capturing several variables.

Should we:
- Split these classes out into nested classes (adding some boilerplate for each variable captured)
- Leave them as anonymous classes (potentially reducing readability)

**Comment by therabidsquirel** [comment]
I think it's better to make them nested classes if they're that big. I think the benefit to readability is definitely worth any cost of passing variables to them.

**Comment by ryant26** [comment]
This is kind of why there isn't really a hard and fast rule about the size we use for anonymous classes more of a guideline. In my opinion extracting that anonymous class out of MultiCallback into a nested class would reduce the readability.

I think we just have to use our judgement. In the case of MultiCallback that anonymous class is very related to it's surrounding code so seeing it in context makes sense. 

The places we should avoid using long annon classes is like an activity where you have some type of listener or callback that doesn't really relate to the surrounding code except that you are setting up callbacks / listeners in that section. The code inside the annon class is out of context, so you might as well make it nested anyway.

**Comment by therabidsquirel** [comment]
Hm, I didn't really think about the context anonymous classes would be in. I'm leaning more towards agreeing with @ryant26 now.

**Comment by TheLastBanana** [comment]
Yeah, I agree with @ryant26. Especially if captured variables are being used, that implies that there's some important contextual information.
