### ISSUE TITLE
Move approver UUID from ApproverComment to the Claim itself

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#81]
[As explained by Ken Wong](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=479244#p1240866), a claim can only have one approver. As a result, keeping a separate Approver for each ApproverComment is redundant.

**Comment by kdbanman** [comment]
Also related to that redundancy, the "Last Approver" string in the Claim Info UI should be changed to just "Approver"
