### ISSUE TITLE
All non-Login activities should observe the DataSource, repopulating on `update()`.

### ISSUE THREAD

**Issue by kdbanman** [CMPUT301W15T07/TravelTracker#84]
Currently, only ClaimsListActivity and ExpenseItemsListActivity are currently Observers of the data source.  All activities except the login activity be observers of the data source, because all their Views need to be repopulated every time the DataSource notices a model update.

For example, in ClaimInfoActivity:

```java
// this will be called *every* time *any* model object changes
@Override
public void update(DataSource datasource) {
  // no need to use the passed datasource - activity already has a reference.
  
  // on some activities, this block will be executed **OFTEN** (i.e. every keypress),
  // so this probably shouldn't be an asynchronous doom block.
}
```

**Comment by kdbanman** [comment]
Strange unit testing problem related to Observers.  By making the ClaimInfoActivity observe the datasource for changes, 2 tests break:

- `testSetExpenseClaimEndDate()`
- `testSetExpenseClaimStartDate()`

However, the in-app behaviour is fine - the dates change as expected.  The changes made are as follows.

```java
public class ClaimInfoActivity extends TravelTrackerActivity implements Observer<DataSource> {

  public void onCreate() {
    // ...
    datasource.addObserver(this);
  }

  @Override
  public void update() {
    datasource.getClaim(claimID, new ClaimCallback());
  }

}
```

**Comment by kdbanman** [comment]
Check out the linked commit (branch `observer-fix`) to see for yourself.

**Comment by TheLastBanana** [comment]
I've solved the problem with those test cases. ClaimInfoActivity now observes the DataSource as expected.

**Comment by TheLastBanana** [comment]
I also added this to the remaining activities 2dde7ba247f75bb64231f630a29221ebd4f40bf7, and it appears to be working. I think we can close this issue unless anybody finds any problems.
