### ISSUE TITLE
Disable editing of claims when the status is Submitted or Approved.

### ISSUE THREAD

**Issue by therabidsquirel** [CMPUT301W15T07/TravelTracker#85]
All of these need to be disabled if the clam cannot be edited.

- ~~Editing claim start and end dates~~
- ~~Adding new destinations~~
- ~~Editing destinations~~
- Adding new expense items
- Editing expense items
- Deleting expense items
- ~~Submitting the claim~~

The user should still be allowed to delete the claim.

**Comment by TheLastBanana** [comment]
I fixed ClaimInfoActivity to disable editing in SUBMITTED and APPROVED status claims (414db46e81d77034e0d0a9470531d4d4dcef8c41).

**Comment by kdbanman** [comment]
These should be fixed:

From the expense item list, items should not be

- addable
- deletable

From the expense item info,  items should not be

- editable
- deletable

**Comment by therabidsquirel** [comment]
Menu buttons hidden in 588d46d. What's left:

From the expense item list, items should not be

- deletable

From the expense item info,  items should not be

- editable

**Comment by therabidsquirel** [comment]
Deletion from list disabled in 3c1df78. What's left:

From the expense item info,  items should not be

- editable

I'm working on this.

**Comment by therabidsquirel** [comment]
Complete now except for the two spinners.

**Comment by therabidsquirel** [comment]
Closed by f4e4899.
