### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by kuzi117** [CMPUT301W15T07/TravelTracker#9]
So, after debating with Elliot for the last ten minutes we've come to the conclusion that we should set some sort of style guide up.
Google has a style guide [here](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html) that looks all right but it doesn't define some things I'd like to talk about.

* Nested/Anonymous classes:
  * When should I define a class in-line as opposed to separately (end of the class)? I feel like in-line is sort of cluttery sometimes but I understand the value of putting something right there and having access to the enclosing scope (sometimes also bad).
* Javadoc style:
  * We need these (as a requirement) but how much? File headers are required, but do we want a description for every class and attribute/method? Getters/setters included?

Any one else got some questions?

**Comment by ryant26** [comment]
Here is what GE does for their java code (My Last Workterm):

Nested / Anonymous classes:
- Use a nested class when there is absolutely no opportunity for code reuse in that class and a nested class makes the code more readable

Javadoc Style
- All public methods have javadoc with params and returns, description if method name isn't enough (Except Getters and Setters)

- Important private methods or private methods that get used a lot get javadoc

I'm okay with that convention? Anyone have other experience with javadoc they prefer?

**Comment by TheLastBanana** [comment]
That convention sounds pretty sane to me. My only concern is whether our TA will consider the documentation incomplete if some private methods aren't documented. Assuming that isn't a problem, though, I think avoiding excessive documentation is a good thing.

**Comment by kdbanman** [comment]
I second Elliot's position - sounds good as long as the TA is happy.

A style guide would be excellent. Regarding inner classes, I feel its almost always a readability and maintainability disadvantage to leave them anonymous.  Even if they're one-off, I try to name them accurately, nest them as private classes, and give them only the data they need.

**Comment by kuzi117** [comment]
See I would like the "even if one off, nest them" approach because I feel like it's just cleaner.

I think I'm misunderstanding what @ryant26's saying a bit. Are you contrasting nested classes with classes defined in a separate file when you say no reusability or are you saying we should use anonymous classes in the case of a one off and a nested class if we use the same code more than once in a parent class?

Once we get this finalized I'd like to put this in the wiki.

**Comment by ryant26** [comment]
Basically I was saying this:
1.) Use an anonymous class when it improves readability, like button listeners. (and other 1-liners)
2.) Use a nested class when you have more than 1 method to implement (anonymous class readability would suffer) but the code can't be extracted into a standalone class because it will never be reused. Like maybe a gesture listener.
3.) Use a standalone class when there are opportunities to reuse the code (). Like adapters.

(So I'm slightly more pro anonymous-class than what @kdbanman is suggesting)

**Comment by kuzi117** [comment]
Thanks, that was a good explanation actually. Personally I'd prefer what @kdbanman is suggesting, but I'll leave it up to a vote and then follow whatever we decide on.

**Comment by therabidsquirel** [comment]
I second what Ryan is saying.

**Comment by kdbanman** [comment]
I think single method one liners are pretty reasonable to leave anonymous.  I retract and vote @ryant26

**Comment by kuzi117** [comment]
So instead is there a threshold of lines when we should go to nested even if it's a single method?

**Comment by kdbanman** [comment]
When it feels bad.  If you feel the need to have whitespace or comments for semantic clarity, pull it out and give it a name. Probably 3ish?

**Comment by kuzi117** [comment]
I can deal with that. Should I just close and go to wiki with it then?

**Comment by ryant26** [comment]
I like that rule. I'd say wiki it.

**Comment by kuzi117** [comment]
I went with the round number of 5 over 3, I felt like 2 extra lines isn't a big deal and it'll give you some code to work with. You can always choose to refactor at less if you feel like readability suffers before 5.

If you truly have an issue with 5 repoen the issue and we can discuss, but for now I'm closing #9.
