### ISSUE TITLE
Add Expense Item from ClaimInfoActivity Menu does not have any effect

### ISSUE THREAD

**Issue by ryant26** [CMPUT301W15T07/TravelTracker#93]
The convenience button "Add Expense Item" inside the menu on ClaimInfoActivity currently does nothing.

**Comment by therabidsquirel** [comment]
I brought this up in a comment on #19. It should be mostly a copy/paste from ExpenseItemsListActivity's menu, as they both have that button. I'll look at it.

**Comment by ryant26** [comment]
@therabidsquirel I had partially implemented it, but backing out caused a crash. I think that is too much work for 2 hours before it's due. 

Eventually we will need to implement whatever method you can use to send an intent to go back

**Comment by therabidsquirel** [comment]
I've almost finished this. It will function exactly like adding a new item from ExpenseItemsListActivity. That probably means it will crash, bu fixing the crash issue will fix adding from both activities.

**Comment by therabidsquirel** [comment]
Done in 72ddc3b. It still crashes, when trying to leave creating the new expense item, but this is an issue with #19.
