### ISSUE TITLE
Save name in login screen

### ISSUE THREAD

**Issue by TheLastBanana** [CMPUT301W15T07/TravelTracker#99]

**Comment by therabidsquirel** [comment]
Currently, the user's name and role are only "remembered" in LoginActivity when the user backs from ClaimsListActivity to LoginActivity. Hitting the Sign Out menu button in any of the activities does not preserve either of the fields. At the very least, Sign Out should preserve the fields I feel.

Do we really care to remember the last user signed in, should they close the app or it crashes? We'd only need to store locally too, as the last user signed in is device-specific. It would be fairly trivial to just save the UserData object to a special last_user file or something when the login button is hit, then always check that file upon starting LoginActivity.

I can go ahead and make these changes, if no one disagrees.
